Backport 23fe2ece586d3ed750e905e1b71a2cd1da91f335
openjdk/jdk21u pull request #308
Opened 2023-10-31 11:56 UTC by MBaesken

os_aix.cpp diff in stride

2023-11-03 15:16 UTC, phohensee requested changes
The deletion of the header comment on os::dll_load is missing from the backport.

2023-11-21 16:37 UTC, MBaesken commented
> The deletion of the header comment on os::dll_load is missing from the backport.

sorry maybe I miss something ?

https://github.com/openjdk/jdk/commit/23fe2ece586d3ed750e905e1b71a2cd1da91f335

changes only cpp files, no header .
And the comment from os_aix.cpp is present ?

2023-11-21 21:11 UTC, phohensee commented
Sorry for being unclear. I meant the comment ahead of the definition of os:dll_load at lines 1104-1105 in os_aix.cpp is deleted by the original commit.
```
// Loads .dll/.so and in case of error it checks if .dll/.so was built
// for the same architecture as Hotspot is running on.
```
They're still in the backport version at lines 1101-1102.

2023-11-22 07:55 UTC, MBaesken commented
Thanks Paul, I removed the comment lines.

2023-11-24 00:40 UTC, phohensee approved these changes

2023-11-24 08:10 UTC, MBaesken commented
/integrate

2023-11-24 08:11 UTC, closed without merging

2023-11-30 12:02 UTC, TheRealMDoerr commented
This backport introduced a bug in 21.0.2: [JDK-8320830](https://bugs.openjdk.org/browse/JDK-8320830)