Backport 8e4e6b056c5ecf731f84a71e4e319d2a27734ec2
openjdk/jdk21u pull request #6
Opened 2023-07-02 19:40 UTC by zhengyu123

A clean backport to fix memory leak.

2023-07-05 19:10 UTC, coleenp approved these changes
This looks good.

2023-07-06 20:57 UTC, coleenp commented
@zhengyu123 did you want to backport this to 21 or 21u1?

2023-07-07 14:47 UTC, coleenp requested changes
In case you didn't see my comment, can you backport this to 21 instead?

2023-07-07 15:16 UTC, zhengyu123 commented
> In case you didn't see my comment, can you backport this to 21 instead?

Sorry, missed early comment. Will backport to 21

2023-07-07 15:46 UTC, closed without merging

2023-07-07 15:47 UTC, zhengyu123 commented
Backport to 21 instead.